# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('code', models.TextField()),
                ('slug', models.SlugField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True)),
                ('content', models.TextField()),
                ('slug', models.SlugField(editable=False)),
                ('submitted', models.DateField(default=django.utils.timezone.now)),
                ('topic', models.CharField(max_length=40)),
                ('almanac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almanac.Almanac')),
            ],
        ),
        migrations.AddField(
            model_name='example',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almanac.Post'),
        ),
    ]
