# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0002_auto_20170531_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
    ]
