# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0005_auto_20170611_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='output',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
