# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0007_auto_20170715_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='from_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
