# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0008_auto_20170715_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
