# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0009_auto_20170715_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
