# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0011_post_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='almanac',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
