# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0012_almanac_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('rank',)},
        ),
    ]
