# Generated by Django 2.0.1 on 2018-01-06 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0013_auto_20170725_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['almanac', 'rank']},
        ),
    ]
