# Generated by Django 2.0.1 on 2018-01-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0014_auto_20180106_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almanac',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
